### ISSUE TITLE
VMWare workstation windows 11 guest freezes sometimes during shutdown/reboot?

### ISSUE THREAD

**Issue by subvert0r** [tandasat/MiniVisorPkg#17]
I replicate it by doing this:

In VMWare workstation, Load the minivisor.efi, load the windows boot manager (latest win 11), then after the machine boots, wait for 30-60 seconds, then try to reboot. 20% of times the VMware guest just freezes, and doesn't crash so no crash log either (either vmware crash log or windows crash dump). It just freezes when the screen goes black after you click on reboot after 2-3 seconds?

Anyone experienced something like this? 

(Yes I have enabled nested virtualization)

**Comment by tandasat** [comment]
That looks correct. TLFS is performance optimization -- so technically the system will run less efficiently but you will never notice this. I have not seen or heard of any issues with suppressing TLFS.

**Comment by tandasat** [comment]
That's good to hear the issue is gone. I have pushed the change to main https://github.com/tandasat/MiniVisorPkg/commit/4ec21d6efae00e82e70b5acfa8dcdaa94f06a63c

I do not plan to add AMD support to this project. It really not worth supporting both processors in the same code base to me. You can still find comparable projects to this for AMD on my repo: 
https://github.com/tandasat/barevisor (UEFI and Windows)
https://github.com/tandasat/HelloAmdHvPkg (UEFI)
https://github.com/tandasat/SimpleSvm (Windows)
