### ISSUE TITLE
Implementing EPT Shadow Hooks

### ISSUE THREAD

**Issue by Seegee** [tandasat/MiniVisorPkg#5]
I am wondering if you could give a high level overview on what would need to be done to port the EPT shadow hooking implementation from [DDIMon](https://github.com/tandasat/DdiMon) to MiniVisorPkg. Being that MiniVisorPkg runs in UEFI, and HyperPlatform is a Windows driver, what changes would need to be made to DdiMon in order for it to work in the context of a UEFI hypervisor like MiniVisorPkg?

**Comment by tandasat** [comment]
The primary difference is that you will have to locate and hook the guest virtual address space, which is not smoothly accessible from the host. 

That part can be achieved by code snippet posted in https://github.com/tandasat/MiniVisorPkg/issues/4. This will let you to hook code in the guest virtual address space. From there, I would add the VMCALL that manipulate EPT of the given page so that read and write against the page is redirected to an intact page. This would essentially be the same VMCALL as `kShEnablePageShadowing` . Then, `InstallHook ` in the above link would use this interface to ask the host to hide the hook she just installed. 

Everything else should remain the same. In other words, only `DdimonInitialization` equivalent parts need major refactoring, so that type-1 VMM operating in a different address space can deal with the guest address space.

**Comment by tandasat** [comment]
2nd thoughts; for locating the hook target in the guest virtual address, it will be simpler to just write a client program for the operating system. That would locate the address of the target,  instead of using the guest agent I wrote above, then ask the host to hide the hook (or to both hook code and hide it)

The guest agent bit is useful for running code during the early boot stage where you have no option to run the other program. This is not required for hooking things stealthily.

Closing as I outline what I think the most significant differences and possible resolutions.
